### ISSUE TITLE
Setup internationalization to support multiple languages.

### ISSUE THREAD

**Issue by janithRS** [lk-gov-health-hiu/project-nhdx#21]
**Is your feature request related to a problem? Please describe.**
Set up i18n for NEHR client.

**Describe the solution you'd like**

https://react.i18next.com/

**Describe alternatives you've considered**

**Additional context**

**Comment by sameeragunarathne** [comment]
Strings used in the app are mentioned in here https://docs.google.com/spreadsheets/d/1EUjABPUtNBeaaqmIA_FgHshLtdl3L1En2CBLrNSJwrA/edit#gid=0
